name: Website Build with Secret Injection

on:
  push:
    branches: [ main, develop ]
    paths: 
      - '**'
      - '.github/workflows/web-build-secrets.yml'
  pull_request:
    branches: [ main ]
    paths: 
      - '**'

jobs:
  web-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
          
      - name: Install Dependencies
        run: npm ci
          
      - name: Inject Website Secrets
        env:
          # Public variables (safe to expose in client)
          NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_NEW }}
          NEXT_PUBLIC_GOOGLE_ADS_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_ADS_ID_NEW }}
          NEXT_PUBLIC_FACEBOOK_PIXEL_ID: ${{ secrets.NEXT_PUBLIC_FACEBOOK_PIXEL_ID_NEW }}
          NEXT_PUBLIC_APPSFLYER_DEV_KEY: ${{ secrets.NEXT_PUBLIC_APPSFLYER_DEV_KEY_NEW }}
          NEXT_PUBLIC_APPSFLYER_APP_ID: ${{ secrets.NEXT_PUBLIC_APPSFLYER_APP_ID_NEW }}
          NEXT_PUBLIC_SMARTLOOK_PROJECT_KEY: ${{ secrets.NEXT_PUBLIC_SMARTLOOK_PROJECT_KEY_NEW }}
          NEXT_PUBLIC_AMPLITUDE_API_KEY: ${{ secrets.NEXT_PUBLIC_AMPLITUDE_API_KEY_NEW }}
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY_NEW }}
          
          # Server-only variables (not exposed in client)
          STRAPI_API_KEY: ${{ secrets.STRAPI_API_KEY_NEW }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY_NEW }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY_NEW }}
        run: |
          # Create .env.local with all secrets
          cat > .env.local << EOF
          NEXT_PUBLIC_GOOGLE_ANALYTICS=$NEXT_PUBLIC_GOOGLE_ANALYTICS
          NEXT_PUBLIC_GOOGLE_ADS_ID=$NEXT_PUBLIC_GOOGLE_ADS_ID
          NEXT_PUBLIC_FACEBOOK_PIXEL_ID=$NEXT_PUBLIC_FACEBOOK_PIXEL_ID
          NEXT_PUBLIC_APPSFLYER_DEV_KEY=$NEXT_PUBLIC_APPSFLYER_DEV_KEY
          NEXT_PUBLIC_APPSFLYER_APP_ID=$NEXT_PUBLIC_APPSFLYER_APP_ID
          NEXT_PUBLIC_SMARTLOOK_PROJECT_KEY=$NEXT_PUBLIC_SMARTLOOK_PROJECT_KEY
          NEXT_PUBLIC_AMPLITUDE_API_KEY=$NEXT_PUBLIC_AMPLITUDE_API_KEY
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
          STRAPI_API_KEY=$STRAPI_API_KEY
          SENDGRID_API_KEY=$SENDGRID_API_KEY
          GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY
          EOF
          
      - name: Build Website
        run: npm run build
          
      - name: Verify No Secrets in Build
        run: |
          # Scan built files for exposed secrets
          grep -r "2SZh8fW3XqbwL8DGvQirV5" .next || echo "✅ No AppsFlyer key found"
          grep -r "2600309206821382" .next || echo "✅ No Facebook Pixel ID found"